### PR TITLE
Update Community Health

### PR DESCRIPTION
**Pull request by BadgerOnABike**
Provide consistent docs across all repos

### CODE REVIEW

**Comment by BadgerOnABike** [comment]
What do you think @spydmobile shall we give it a shot!

**Comment by spydmobile** [comment]
@BadgerOnABike hi, no I think you still need to create the folder /.github/.github/ and move them into it first.

**Comment by spydmobile** [comment]
@BadgerOnABike sorry - the two template folders NOT the profile folder

**Comment by BadgerOnABike** [comment]
You'll see that change now

**Pull request merged**
